"use client";
import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useRouter, usePathname } from "next/navigation";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// I HAD TO COMMENT THIS OUT TO USE useEffect for "getProfile()"

// export const metadata: Metadata = {
//   title: "Salumi Tracker",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const pathname = usePathname();

  if (
    !document.cookie.includes("logged_in=true") &&
    pathname !== "/login" &&
    pathname !== "/register"
  ) {
    router.push("/login");
  }

  const checkAuth = () => {
    try {
      if (
        !document.cookie.includes("logged_in=true") &&
        pathname !== "/register" &&
        pathname !== "/login"
      ) {
        console.log(pathname !== "/register");
        router.push("/logout");
      }
    } catch (e) {
      console.log("Error checking authentication status:", e);
    }
  };

  // useEffect(() => {
  //   checkAuth();
  //   const interval = setInterval(checkAuth, 6000);
  //   return () => {
  //     clearInterval(interval);
  //   };
  // }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          {children}
          <ReactQueryDevtools />
        </QueryClientProvider>
      </body>
    </html>
  );
}
