"use client";

import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navigation/navbar";
import { useEffect } from "react";
import { useState } from "react";
import Sidebar from "@/components/navigation/sidebar";
import { IresponseData, IprofileData } from "../interfaces/interfaces";

const inter = Inter({ subsets: ["latin"] });

// I HAD TO COMMENT THIS OUT TO USE useEffect for "getProfile()"

// export const metadata: Metadata = {
//   title: "Salumi Tracker",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [profileData, setProfileData] = useState<IprofileData>();

  useEffect(() => {
    const getProfile = async () => {
      const response = await fetch("http://localhost:8000/api/users/me", {
        method: "GET",
        credentials: "include",
      });
      const data: IresponseData = await response.json();
      if (data.status) {
        setProfileData(data.data);
        sessionStorage.setItem("email", data.data.user.email);
        sessionStorage.setItem("name", data.data.user.name);
      } else {
        console.log("request failed");
        location.href = "/login";
      }
    };

    if (document.cookie === "logged_in=true") {
      getProfile();
    } else if (location.href !== "http://localhost:3000/login") {
      location.href = "/login";
    }

    if (
      (document.cookie === "logged_in=true" &&
        window.location.href === "http://localhost:3000/register") ||
      (document.cookie === "logged_in=true" &&
        window.location.href === "http://localhost:3000/login")
    ) {
      location.href = "/";
    }
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        {profileData ? (
          <div className="flex flex-row">
            <Sidebar />
            <div className="flex-col w-full flex">
              <Navbar person={profileData} />
              {children}
            </div>
          </div>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
