"use client";

import { useEffect } from "react";
import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useRouter, usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// I HAD TO COMMENT THIS OUT TO USE useEffect for "getProfile()"

// export const metadata: Metadata = {
//   title: "Salumi Tracker",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const pathname = usePathname();

  if (
    !document.cookie.includes("logged_in=true") &&
    pathname !== "/login" &&
    pathname !== "/register"
  ) {
    router.push("/login");
  }

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
