"use client";

import "../../app/globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navigation/navbar";
import { useEffect } from "react";
import { useState } from "react";
import Sidebar from "@/components/navigation/sidebar";
import { IresponseData, IprofileData } from "../../interfaces/interfaces";
import { useRouter } from "next/navigation";

// I HAD TO COMMENT THIS OUT TO USE useEffect for "getProfile()"

// export const metadata: Metadata = {
//   title: "Salumi Tracker",
//   description: "Generated by create next app",
// };

export default function PrivateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [profileData, setProfileData] = useState<IprofileData>();
  const router = useRouter();

  console.log("LSJDKSLDJLSDJLSDJLSJ");
  useEffect(() => {
    const getProfile = async () => {
      const response = await fetch("http://localhost:8000/api/users/me", {
        method: "GET",
        credentials: "include",
      });
      const data: IresponseData = await response.json();
      if (data.status) {
        setProfileData(data.data);
        sessionStorage.setItem("email", data.data.user.email);
        sessionStorage.setItem("name", data.data.user.name);
      } else {
        console.log("request failed");
        router.push("/login");
      }
    };
    console.log("COOLIE", document.cookie);
    if (document.cookie.includes("logged_in=true")) {
      getProfile();
      //usepathname instead of location.href
    } else if (location.href !== "http://localhost:3000/login") {
      router.push("/login");
    }

    if (
      (document.cookie === "logged_in=true" &&
        window.location.href === "http://localhost:3000/register") ||
      (document.cookie === "logged_in=true" &&
        window.location.href === "http://localhost:3000/login")
    ) {
      router.push("/");
    }
  }, []);

  return (
    <div className="flex flex-row">
      <Sidebar />
      <div className="flex-col w-full flex">
        <Navbar person={profileData} />
        {children}
      </div>
    </div>
  );
}
